[tool.poetry]
name = "adell-mri"
version = "0.1.0"
description = "A deep-learning library built with torch, lightning and MONAI for medical imaging."
authors = ["josegcpa <jose.almeida@research.fchampalimaud.pt>",
           "NMVRodrigues"]
license = "LICENSE"
readme = "README.md"
packages = [{include = "lib"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
dvc = "2.45.1"
einops = "0.7.0"
hydra-core = "1.3.2"
itk = "5.3.0"
lightning = "2.1.1"
monai = "1.3.0"
multiprocess = "0.70.13"
nibabel = "5.1.0"
numpy = "1.23.5"
omegaconf = "2.3.0"
pandas = "1.4.2"
panel = "1.2.3"
Pillow = "10"
pydicom = "2.3.0"
pytest = "7.2.0"
PyYAML = "6.0"
scikit_image = "0.19.2"
scikit_learn = "1.3.0"
scipy = "1.11.3"
SimpleITK = "2.3.1"
torch = "2.0.1"
torchmetrics = "1.2.0"
tqdm = "4.64.1"
generative = { git = "https://github.com/Project-MONAI/GenerativeModels.git", tag = "0.2.2" }

[tool.poetry.scripts]
adell_mri = "lib.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
