python3 u-net-train.py \
    --dataset_json dataset_information/bb.pi-cai.clinical.json \
    --image_keys image image_1 image_2 \
    --mask_keys lesion_merge \
    --target_spacing 0.5 0.5 3.6000006198883057 \
    --crop_size 256 256 19.166662987945223 \
    --possible_labels 0 1 2 3 4 5 \
    --positive_labels 1 2 3 4 5 \
    --config_file config/u-net-3d-simple.yaml \
    --dev cuda:1 \
    --seed 42 \
    --n_workers 4 \
    --loss_gamma 1.0 \
    --loss_comb 0.5 \
    --max_epochs 250 \
    --folds $(cat dataset_information/folds-ids.csv | tr '\n' ' ') \
    --class_weights adaptive \
    --augment \
    --adc_factor 0.3333333333333333 \
    --adc_image_keys image_1 \
    --n_devices 1 \
    --deep_supervision \
    --project_name picai_pca_lesion_segmentation \
    --summary_name unet.simple \
    --checkpoint_name unet.simple \
    --checkpoint_dir models/unet \
    --check_val_every_n_epoch 5 \
    --accumulate_grad_batches 2 \
    --use_val_as_train_val \
    --resume_from_last

python3 u-net-train.py \
    --dataset_json dataset_information/bb.pi-cai.clinical.json \
    --image_keys image image_1 image_2 \
    --mask_keys lesion_merge \
    --target_spacing 0.5 0.5 3.6000006198883057 \
    --crop_size 256 256 19.166662987945223 \
    --possible_labels 0 1 2 3 4 5 \
    --positive_labels 1 2 3 4 5 \
    --config_file config/u-net-3d.yaml \
    --dev cuda:1 \
    --seed 42 \
    --n_workers 4 \
    --loss_gamma 1.0 \
    --loss_comb 0.5 \
    --max_epochs 400 \
    --folds $(cat dataset_information/folds-ids.csv | tr '\n' ' ') \
    --class_weights adaptive \
    --augment \
    --adc_factor 0.3333333333333333 \
    --adc_image_keys image_1 \
    --n_devices 1 \
    --deep_supervision \
    --project_name picai_pca_lesion_segmentation \
    --summary_name unet \
    --checkpoint_name unet \
    --checkpoint_dir models/unet \
    --check_val_every_n_epoch 5 \
    --accumulate_grad_batches 2 \
    --use_val_as_train_val \
    --resume_from_last
