---
spatial_dimensions: 3
resnet_structure: [[32,64,5,2],[64,128,3,3],[128,256,3,2],[256,512,3,2]]
maxpool_structure: [[2,2,2],[2,2,2],[2,2,2],[2,2,1]]
learning_rate: 0.001
batch_size: 16
weight_decay: 0.005
batch_ensemble: 4
res_type: "resnet"