---
spatial_dimensions: 3
conv_type: "regular"
link_type: "residual"
upscale_type: "transpose"
norm_type: "instance"
interpolation: "bilinear"
padding: 1
dropout_param: 0.15
activation_fn: "swish"
n_channels: 1
depth: [32,32,64,128,256]
kernel_sizes: [3,3,3,3,3]
strides: [2,2,2,2,2]
learning_rate: 0.0005
batch_size: 2
weight_decay: 0.005
loss_fn: 
  "dice":
    eps: 1.0e-6
    smooth: 1.0e-5
  "focal":
    gamma: 1.0
    eps: 1.0e-6