---
patch_size: [16,16,4]
number_of_blocks: 9
n_heads: 12
embedding_size: 768
attention_dim: 768
hidden_dim: 768
dropout_rate: 0.1
embed_method: "convolutional"
mlp_structure: [1024]
use_class_token: false
learning_rate: 0.00002
weight_decay: 0.03