---
spatial_dimensions: 3
resnet_structure: [[32,64,[7,7,5],6],[64,128,[7,7,5],6],[128,256,[5,5,3],9],[256,512,3,6]]
maxpool_structure: [[2,2,2],[2,2,2],[2,2,2],[2,2,1]]
learning_rate: 0.001
batch_size: 16
weight_decay: 0.005
#batch_ensemble: 4
res_type: "convnext"