---
patch_size: [16,16,2]
window_size: [32,32,2]
shift_sizes: [[0,1],[0,1],[0,1,0,1],[0,1]]
embedding_size: 256
n_heads: 8
mlp_structure: 3.0
spatial_dimensions: 3
embed_method: "linear"
conv_type: "regular"
link_type: "residual"
upscale_type: "transpose"
norm_type: "instance"
interpolation: "bilinear"
padding: 1
dropout_rate: 0.1
dropout_param: 0
activation_fn: "leaky_relu"
n_channels: 1
depth: [16,32,64,128]
kernel_sizes: [3,3,3,3]
learning_rate: 0.005
batch_size: 3
weight_decay: 0.05
loss_fn: "focal"
