---
spatial_dimensions: 3
conv_type: "regular"
link_type: "residual"
upscale_type: "transpose"
interpolation: "bilinear"
norm_type: "instance"
dropout_type: "uout"
padding: 1
dropout_param: 0.2
activation_fn: "prelu"
n_channels: 1
depth: [32,64,128,256]
kernel_sizes: [3,3,3,3]
strides: [2,2,2,2]
learning_rate: 0.001
batch_size: 8
weight_decay: 0.005
loss_fn: "focal"