---
spatial_dimensions: 2
conv_type: "resnet"
link_type: "residual"
upscale_type: "transpose"
norm_type: "instance"
interpolation: "bilinear"
padding: 1
dropout_param: 0.1
activation_fn: "swish"
n_channels: 1
depth: [32,64,128,256]
kernel_sizes: [3,3,3,3]
strides: [2,2,2,2]
learning_rate: 0.001
batch_size: 4
weight_decay: 0.0005
loss_fn: "focal"