---
spatial_dimensions: 3
conv_type: "sae"
link_type: "residual"
upscale_type: "transpose"
norm_type: "batch"
interpolation: "bilinear"
padding: 1
dropout_param: 0.
activation_fn: "leaky_relu"
n_channels: 1
depth: [16,32,64,128,256,512]
kernel_sizes: [3,3,3,3,3,3]
strides: [[2,2,1],[2,2,1],[2,2,2],[2,2,2],[2,2,1],[2,2,1]]
learning_rate: 0.001
batch_size: 32
weight_decay: 0.0005
loss_fn: "focal"