name: Linting and unit tests

on: 
  push:
    paths:
      - "testing/**"
      - "adell_mri/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    
    - name: Install ruff and pytest
      run: |
        uv add ruff pytest
    
    - name: Lint with ruff
      run: |
        uv run ruff check . --select=E9,F63,F7,F82
    
    - name: Test with pytest
      run: |
        uv run pytest testing